### ISSUE TITLE
Artist page lists correct information

### ISSUE THREAD

**Issue by benry-git** [rianvdm/my-music-next#28]
Example: https://listentomore.com/artist/giants-killed-patrick is me. While the bio speaks to someone completely different.

**Comment by rianvdm** [comment]
Ah that's a ChatGPT hallucination. I have instructions in there to make sure it doesn't do that, but I'll try to make it more robust, or switch to Perplexity.

**Comment by rianvdm** [comment]
For now I've strengthened the OpenAI logic so that it says "I don't know" if it doesn't have information. I might switch to Perplexity down the road, but it's a more expensive API so while this is a side project I don't think I can do that :)
